//
//  MainViewModel.swift
//  App186
//
//  Created by Вячеслав on 9/7/23.
//

import SwiftUI

final class MainViewModel: ObservableObject {
    
    @Published var isDetail: Bool = false
    @Published var selectedLesson: MainModel?
    
    @Published var lessons: [MainModel] = [
    
        MainModel(title: "EU’s top court makes landmark Russian sanctions decision", text: "It’s the first time that EU sanctions have been lifted by a court ruling in relation to a Russian businessman. Previously, such decisions have been made only regarding their sanctioned relatives. The effect of decision 2023/572 remains in relation to Shulgin until the expiration date for filing an appeal or until it is rejected,” the court stated, adding that “the rest of the appeal is dismissed. The EU had targeted Shulgin as a “leading [Russian] businessman” and the CEO of a company “involved in economic sectors that provide a significant source of income” for the Russian government. The bloc also noted when imposing the sanctions that on February 24 – the day Moscow launched its military operation in Ukraine – Shulgin was among a number of Russian businessmen who met with President Vladimir Putin in the Kremlin. However, three days after the introduction of restrictions, Shulgin stepped down as Ozon’s chief executive and resigned from the company’s board of directors. He has since been trying to legally challenge the notion that he is a “leading businessman.” "),
        MainModel(title: "G7 scraps review of Russian oil price cap – Reuters", text: "The price limit on Russian seaborne crude of $60 per barrel was introduced by the EU, G7 countries, and Australia on December 5. It bans Western firms from providing insurance and other services to shipments of Russian crude, unless the cargo is purchased at or below the set price. The EU initially agreed to review the price cap every two months and make adjustments to the scheme, while the G7 said it would review “as appropriate” including “implementation and adherence.” Moscow has responded to the restrictions by outlawing the sale of oil and refined products to buyers that comply with the cap, and redirected most shipments away from the West. India and China emerged as key buyers of Russian crude, while oil exporters have found ways to sell the commodity using domestic or non-Western ships and insurance services, making it difficult for the West to enforce the price cap mechanism."),
        MainModel(title: "Russia accelerates sale of foreign currencies", text: "Russia is due to make a $3 billion Eurobond payment on September 16, the regulator said, noting that most holders will receive payment in rubles, although some may then create additional demand for foreign currency. “Under these conditions, the decision to redistribute foreign currency sales as part of mirroring transactions related to investing [from the National Wealth Fund] will help meet possible additional demand for foreign currency and reduce volatility in the foreign-exchange market during this period,” the statement reads. The Russian ruble strengthened on the central bank’s announcement to 97.59 against the US dollar and 104.81 versus the euro."),
        MainModel(title: "Russia’s McDonald’s replacement eyes China expansion", text: "According to the owner of the Russian franchise, Aleksandr Govor, Vkusno i Tochka received a request from the Chinese city situated across the Amur River from the Russian city of Blagoveshchensk. Under the terms of the agreement between Govor and the US fast-food giant after the latter decided to exit the Russian market, the local group cannot open restaurants of the rebranded chain in countries where McDonald’s operates. According to Govor, McDonald’s supply logistics do not reach the Chinese backcountry region, which has a restaurant shortage. The US fast-food giant announced plans to sell its business in Russia in May 2022 due to intense international pressure after Moscow launched its military operation in Ukraine. McDonald’s sold its 800 restaurants in Russia to Govor, the company’s local licensee, who renamed the food chain Vkusno i Tochka. Govor had previously operated 25 restaurants of the US chain in Siberia. The deal value hasn’t been disclosed, but the new owner said that the amount was much lower than the market price. Under the deal, McDonald’s has the right to buy back its restaurants in Russia within 15 years."),
        MainModel(title: "Chinese travel boom fueling oil-price rise – analyst", text: "Speaking at the Asia Pacific Petroleum Conference (APPEC) in Singapore on Monday, Gary Ross noted that domestic flights in China have reached 110% of their pre-pandemic levels, up from about 75% in the fourth quarter of last year. International flights have also rebounded, from close to zero to about 75% of the level seen prior to pandemic lockdowns. The rebound sharply accelerated after China lifted its ban on group travel to most destinations last month. “You’re gonna have a big increase in jet fuel demand probably of something like 500,000 barrels a day in China alone,” Ross predicted. He noted that road travel in Asia’s biggest economy has also been on the rise, and as local drivers prefer vehicles with traditional engines rather than electric ones for longer trips, demand for gasoline is likely to soar further. “Gasoline sales have been absolutely astonishing during the summer… People are driving like crazy. The year-on-year comparisons are going to be dramatic… I expect a huge increase in demand in the fourth quarter of 2023,” he stated."),
    ]
}
